version: 2

jobs:
  test:
    working_directory: /go/src/github.com/hypermint/erc20
    docker:
      - image: rust:1.37.0-buster
    steps:
      - checkout
      - run:
          name: "build lib"
          command: |
            make build
      - run:
          name: "setup lint tools"
          command: |
            make lint-tools
      - run:
          name: "lint"
          command: |
            make lint
      - run:
          name: "build"
          command: |
            cargo build
      - run:
          name: "test"
          command: |
            cargo test

workflows:
  version: 2
  test-suite:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/
